# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameplay', '0002_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='second_player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='games_second_player', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
